import { Trainer, TrainerSpecialty } from './types';

export const MOCK_TRAINERS: Trainer[] = [
  {
    id: '1',
    name: 'Alexandra Vance',
    location: 'New York, NY',
    specialty: TrainerSpecialty.STRENGTH,
    rating: 4.9,
    reviewCount: 124,
    hourlyRate: 100,
    discountedRate: 50,
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    verified: true,
    availableNow: true,
  },
  {
    id: '2',
    name: 'Julian Blackwood',
    location: 'Brooklyn, NY',
    specialty: TrainerSpecialty.CARDIO,
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 80,
    discountedRate: 40,
    imageUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    verified: true,
    availableNow: false,
  },
  {
    id: '3',
    name: 'Sienna Moretti',
    location: 'Queens, NY',
    specialty: TrainerSpecialty.YOGA,
    rating: 5.0,
    reviewCount: 215,
    hourlyRate: 120,
    discountedRate: 60,
    imageUrl: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    verified: true,
    availableNow: true,
  },
  {
    id: '4',
    name: 'Xavier Sterling',
    location: 'Manhattan, NY',
    specialty: TrainerSpecialty.REHAB,
    rating: 4.9,
    reviewCount: 56,
    hourlyRate: 150,
    discountedRate: 75,
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    verified: true,
    availableNow: false,
  },
  {
    id: '5',
    name: 'Isabella Thorne',
    location: 'Jersey City, NJ',
    specialty: TrainerSpecialty.NUTRITION,
    rating: 4.7,
    reviewCount: 102,
    hourlyRate: 90,
    discountedRate: 45,
    imageUrl: 'https://images.unsplash.com/photo-1594882645126-14020914d58d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    verified: true,
    availableNow: true,
  },
  {
    id: '6',
    name: 'Dominic Rossi',
    location: 'Hoboken, NJ',
    specialty: TrainerSpecialty.STRENGTH,
    rating: 4.8,
    reviewCount: 78,
    hourlyRate: 110,
    discountedRate: 55,
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    verified: true,
    availableNow: true,
  }
];

export const SPECIALTIES = Object.values(TrainerSpecialty);